export const SITE_CONFIG = {
  name: "CuffKings",
  tagline: "Handcrafted Men's Cufflinks & Formal Accessories",
  description:
    "Handcrafted men's cufflinks made in Peshawar, Pakistan. Solid jeweler's brass, cold-cured vitreous enamel, and precision swivel-bar mechanisms across Classical, Signature, and Premium collections.",
  url: process.env.NEXT_PUBLIC_SITE_URL || "https://cuffkings.pk",
  defaultWhatsAppNumber: "923719145871",
  currency: "PKR",
  currencySymbol: "Rs.",
  defaultDeliveryFee: 180,
  revalidateSeconds: 60,
  collections: ["Classical", "Signature", "Premium"] as const,
  cities: [
    "Peshawar",
    "Islamabad",
    "Rawalpindi",
    "Lahore",
    "Karachi",
    "Faisalabad",
    "Multan",
    "Sialkot",
    "Gujranwala",
    "Quetta",
    "Hyderabad",
    "Abbottabad",
    "Mardan",
    "Other",
  ] as const,
} as const;
