export type CollectionCategory = "Classical" | "Signature" | "Premium";
export type CollectionSlug = "classical" | "signature" | "premium";

export interface Product {
  id: string;
  name: string;
  slug: string;
  category: CollectionCategory;
  categorySlug: CollectionSlug;
  description: string;
  price: number;
  compareAtPrice?: number;
  images: string[];
  material: string;
  finish: string;
  color: string;
  shape: string;
  pattern: string;
  isSet: boolean;
  pairsCount: number;
  stock: number;
  sku: string;
  featured: boolean;
  hasPhotography: boolean;
  video?: string;
  heroVideo?: string;
}

/**
 * Price guidance per tier:
 * - Classical: Rs. 700–800
 * - Signature: Rs. 1,000–1,400
 * - Premium: Rs. 1,500–2,500
 */
const products: Product[] = [
  // ==========================================
  // CLASSICAL COLLECTION (17 Products: Rs. 700 - 800)
  // ==========================================
  {
    id: "c-1",
    name: "Classical Minimalist Gold Cufflinks",
    slug: "classical-minimalist-gold-cufflinks",
    category: "Classical",
    categorySlug: "classical",
    description: "Solid brass base with polished gold-tone finish and clean beveled edges for daily formalwear.",
    price: 750,
    images: ["/products/classic1.jpeg", "/products/classic1+.jpeg"],
    material: "Gold-tone metal",
    finish: "Polished",
    color: "Gold",
    shape: "Square",
    pattern: "Minimalist bevel",
    isSet: false,
    pairsCount: 1,
    stock: 14,
    sku: "CK-CLS-001",
    featured: true,
    hasPhotography: true,
  },
  {
    id: "c-2",
    name: "Classical Silver Brushed Cufflinks",
    slug: "classical-silver-brushed-cufflinks",
    category: "Classical",
    categorySlug: "classical",
    description: "Reflective silver plating with satin wire-brushed face and mirror-polished perimeter.",
    price: 780,
    images: ["/products/classic 2.jpeg", "/products/classic 2+.jpeg"],
    material: "Silver-tone metal",
    finish: "Brushed",
    color: "Silver",
    shape: "Rectangular",
    pattern: "Brushed center",
    isSet: false,
    pairsCount: 1,
    stock: 18,
    sku: "CK-CLS-002",
    featured: true,
    hasPhotography: true,
  },
  {
    id: "c-3",
    name: "Classical Gunmetal Sleek Cufflinks",
    slug: "classical-gunmetal-sleek-cufflinks",
    category: "Classical",
    categorySlug: "classical",
    description: "Understated charcoal gunmetal with matte surface treatment and precision filed toggle mechanism.",
    price: 800,
    images: ["/products/classic 3.jpeg", "/products/classic 3+.jpeg"],
    material: "Gunmetal finish",
    finish: "Matte",
    color: "Gunmetal",
    shape: "Square",
    pattern: "Monochrome flat",
    isSet: false,
    pairsCount: 1,
    stock: 12,
    sku: "CK-CLS-003",
    featured: true,
    hasPhotography: true,
  },
  {
    id: "c-4",
    name: "Classical Polished Onyx Tone Cufflinks",
    slug: "classical-polished-onyx-tone-cufflinks",
    category: "Classical",
    categorySlug: "classical",
    description: "Gloss black center bordered by polished silver-tone framing for a timeless black-tie look.",
    price: 750,
    images: ["/products/classic 4.jpeg"],
    material: "Silver-tone metal, black enamel",
    finish: "Polished",
    color: "Silver, Black",
    shape: "Circular",
    pattern: "Flush perimeter",
    isSet: false,
    pairsCount: 1,
    stock: 15,
    sku: "CK-CLS-004",
    featured: false,
    hasPhotography: true,
  },
  {
    id: "c-5",
    name: "Classical Roman Beveled Cufflinks",
    slug: "classical-roman-beveled-cufflinks",
    category: "Classical",
    categorySlug: "classical",
    description: "Clean linear grooving across a polished gold-tone surface with calibrated weight for shirts.",
    price: 790,
    images: ["/products/classic 5.jpeg"],
    material: "Gold-tone metal",
    finish: "Polished",
    color: "Gold",
    shape: "Rectangular",
    pattern: "Linear bevel",
    isSet: false,
    pairsCount: 1,
    stock: 10,
    sku: "CK-CLS-005",
    featured: false,
    hasPhotography: true,
  },
  {
    id: "c-6",
    name: "Classical Executive Silver Cufflinks",
    slug: "classical-executive-silver-cufflinks",
    category: "Classical",
    categorySlug: "classical",
    description: "Classic executive design featuring subtle central step and high-luster rhodium-tone finish.",
    price: 720,
    images: ["/products/classic 6.jpeg"],
    material: "Silver-tone metal",
    finish: "Polished",
    color: "Silver",
    shape: "Square",
    pattern: "Stepped border",
    isSet: false,
    pairsCount: 1,
    stock: 16,
    sku: "CK-CLS-006",
    featured: false,
    hasPhotography: true,
  },
  {
    id: "c-7",
    name: "Classical Satin Stripe Cufflinks",
    slug: "classical-satin-stripe-cufflinks",
    category: "Classical",
    categorySlug: "classical",
    description: "Alternating polished and satin textures create understated contrast suitable for any business suit.",
    price: 760,
    images: ["/products/classic 7.jpeg", "/products/classic 7+.jpeg"],
    material: "Silver-tone metal",
    finish: "Brushed",
    color: "Silver",
    shape: "Rectangular",
    pattern: "Dual stripe",
    isSet: false,
    pairsCount: 1,
    stock: 20,
    sku: "CK-CLS-007",
    featured: true,
    hasPhotography: true,
  },
  {
    id: "c-8",
    name: "Classical Charcoal Inset Cufflinks",
    slug: "classical-charcoal-inset-cufflinks",
    category: "Classical",
    categorySlug: "classical",
    description: "Gunmetal exterior housing a dark grey insert. Durable swivel closure tested for French cuffs.",
    price: 780,
    images: ["/products/classic 8.jpeg"],
    material: "Gunmetal finish",
    finish: "Matte",
    color: "Gunmetal, Grey",
    shape: "Square",
    pattern: "Inset border",
    isSet: false,
    pairsCount: 1,
    stock: 11,
    sku: "CK-CLS-008",
    featured: false,
    hasPhotography: true,
  },
  {
    id: "c-9",
    name: "Classical Golden Radiance Cufflinks",
    slug: "classical-golden-radiance-cufflinks",
    category: "Classical",
    categorySlug: "classical",
    description: "Warm champagne gold plating with diamond-cut edge detailing reflecting subtle light.",
    price: 800,
    images: ["/products/classic 9.jpeg"],
    material: "Gold-tone metal",
    finish: "Polished",
    color: "Gold",
    shape: "Circular",
    pattern: "Radiant border",
    isSet: false,
    pairsCount: 1,
    stock: 13,
    sku: "CK-CLS-009",
    featured: false,
    hasPhotography: true,
  },
  {
    id: "c-10",
    name: "Classical Pure Rhodium Finish Cufflinks",
    slug: "classical-pure-rhodium-finish-cufflinks",
    category: "Classical",
    categorySlug: "classical",
    description: "Minimalist mirror-polished disc designed to hold French cuffs crisp throughout formal dinners.",
    price: 740,
    images: ["/products/classic 10.jpeg"],
    material: "Silver-tone metal",
    finish: "Polished",
    color: "Silver",
    shape: "Circular",
    pattern: "Smooth disc",
    isSet: false,
    pairsCount: 1,
    stock: 19,
    sku: "CK-CLS-010",
    featured: false,
    hasPhotography: true,
  },
  {
    id: "c-11",
    name: "Classical Deep Noir Square Cufflinks",
    slug: "classical-deep-noir-square-cufflinks",
    category: "Classical",
    categorySlug: "classical",
    description: "Smooth black resin center surrounded by polished brass casing. Perfectly proportioned.",
    price: 770,
    images: ["/products/classic 11.jpeg", "/products/classic 11+.jpeg"],
    material: "Gold-tone metal, black resin",
    finish: "Polished",
    color: "Gold, Black",
    shape: "Square",
    pattern: "Framed resin",
    isSet: false,
    pairsCount: 1,
    stock: 15,
    sku: "CK-CLS-011",
    featured: true,
    hasPhotography: true,
  },
  {
    id: "c-12",
    name: "Classical Matte Platinum Tone Cufflinks",
    slug: "classical-matte-platinum-tone-cufflinks",
    category: "Classical",
    categorySlug: "classical",
    description: "Sophisticated platinum tone finish with subtle chamfered corners and calibrated pair weight.",
    price: 790,
    images: ["/products/classic 12.jpeg"],
    material: "Silver-tone metal",
    finish: "Matte",
    color: "Silver",
    shape: "Rectangular",
    pattern: "Chamfered corners",
    isSet: false,
    pairsCount: 1,
    stock: 12,
    sku: "CK-CLS-012",
    featured: false,
    hasPhotography: true,
  },
  {
    id: "c-13",
    name: "Classical Fine Grid Silver Cufflinks",
    slug: "classical-fine-grid-silver-cufflinks",
    category: "Classical",
    categorySlug: "classical",
    description: "Micro-grid surface pattern providing subtle tactile grip and elegant reflection under chandeliers.",
    price: 800,
    images: ["/products/classic 13.jpeg", "/products/classic 13+.jpeg"],
    material: "Silver-tone metal",
    finish: "Engraved",
    color: "Silver",
    shape: "Square",
    pattern: "Micro-grid",
    isSet: false,
    pairsCount: 1,
    stock: 14,
    sku: "CK-CLS-013",
    featured: true,
    hasPhotography: true,
  },
  {
    id: "c-14",
    name: "Classical Heritage Gilt Cufflinks",
    slug: "classical-heritage-gilt-cufflinks",
    category: "Classical",
    categorySlug: "classical",
    description: "Traditional formal wear essential with durable gold-tone electroplating and rounded borders.",
    price: 730,
    images: ["/products/classic 14.jpeg"],
    material: "Gold-tone metal",
    finish: "Polished",
    color: "Gold",
    shape: "Oval",
    pattern: "Smooth dome",
    isSet: false,
    pairsCount: 1,
    stock: 9,
    sku: "CK-CLS-014",
    featured: false,
    hasPhotography: true,
  },
  {
    id: "c-15",
    name: "Classical Brushed Obsidian Cufflinks",
    slug: "classical-brushed-obsidian-cufflinks",
    category: "Classical",
    categorySlug: "classical",
    description: "Deep charcoal tone with horizontal graining. Designed for charcoal or black evening suiting.",
    price: 760,
    images: ["/products/classic 15.jpeg"],
    material: "Gunmetal finish",
    finish: "Brushed",
    color: "Gunmetal",
    shape: "Rectangular",
    pattern: "Horizontal brush",
    isSet: false,
    pairsCount: 1,
    stock: 17,
    sku: "CK-CLS-015",
    featured: false,
    hasPhotography: true,
  },
  {
    id: "c-16",
    name: "Classical Polished Dual Bevel Cufflinks",
    slug: "classical-polished-dual-bevel-cufflinks",
    category: "Classical",
    categorySlug: "classical",
    description: "Precision-machined double beveled edges providing architectural depth in a compact form.",
    price: 780,
    images: ["/products/classic 16.jpeg"],
    material: "Silver-tone metal",
    finish: "Polished",
    color: "Silver",
    shape: "Square",
    pattern: "Dual bevel",
    isSet: false,
    pairsCount: 1,
    stock: 11,
    sku: "CK-CLS-016",
    featured: false,
    hasPhotography: true,
  },
  {
    id: "c-17",
    name: "Classical Formal Bar Cufflinks",
    slug: "classical-formal-bar-cufflinks",
    category: "Classical",
    categorySlug: "classical",
    description: "Subtle central bar detail accentuating cuff lines with refined dignity and reliable tension.",
    price: 750,
    images: ["/products/classic 17.jpeg"],
    material: "Silver-tone metal",
    finish: "Polished",
    color: "Silver",
    shape: "Rectangular",
    pattern: "Center ridge",
    isSet: false,
    pairsCount: 1,
    stock: 13,
    sku: "CK-CLS-017",
    featured: false,
    hasPhotography: true,
  },

  // ==========================================
  // SIGNATURE COLLECTION (33 Products: Rs. 1,000 - 1,400)
  // ==========================================
  {
    id: "s-1",
    name: "Signature Sapphire Floral Cufflinks",
    slug: "signature-sapphire-floral-cufflinks",
    category: "Signature",
    categorySlug: "signature",
    description: "Deep mineral blue enamel with hand-finished scrollwork set in a polished silver bezel.",
    price: 1250,
    images: ["/products/signature 1.jpeg"],
    material: "Silver-tone metal, blue enamel",
    finish: "Engraved",
    color: "Silver, Blue",
    shape: "Circular",
    pattern: "Floral scrollwork",
    isSet: false,
    pairsCount: 1,
    stock: 14,
    sku: "CK-SIG-001",
    featured: true,
    hasPhotography: true,
  },
  {
    id: "s-2",
    name: "Signature Emerald Tone Enamel Cufflinks",
    slug: "signature-emerald-tone-enamel-cufflinks",
    category: "Signature",
    categorySlug: "signature",
    description: "Rich green enamel framed by gold-tone borders with satin side accents.",
    price: 1200,
    images: ["/products/signature 2.jpeg"],
    material: "Gold-tone metal, green enamel",
    finish: "Polished",
    color: "Gold, Green",
    shape: "Square",
    pattern: "Enamel inlay",
    isSet: false,
    pairsCount: 1,
    stock: 11,
    sku: "CK-SIG-002",
    featured: true,
    hasPhotography: true,
  },
  {
    id: "s-3",
    name: "Signature Guilloché Silver Cufflinks",
    slug: "signature-guilloche-silver-cufflinks",
    category: "Signature",
    categorySlug: "signature",
    description: "Intricate sunburst guilloché engraving radiating from center under directional light.",
    price: 1300,
    images: ["/products/signature 3.jpeg"],
    material: "Silver-tone metal",
    finish: "Engraved",
    color: "Silver",
    shape: "Circular",
    pattern: "Guilloché sunburst",
    isSet: false,
    pairsCount: 1,
    stock: 16,
    sku: "CK-SIG-003",
    featured: false,
    hasPhotography: true,
  },
  {
    id: "s-4",
    name: "Signature Midnight Onyx Octagon Cufflinks",
    slug: "signature-midnight-onyx-octagon-cufflinks",
    category: "Signature",
    categorySlug: "signature",
    description: "Faceted octagonal border enclosing deep black mineral inlay with polished edge fillets.",
    price: 1350,
    images: ["/products/signature 4.jpeg"],
    material: "Gold-tone metal, black enamel",
    finish: "Polished",
    color: "Gold, Black",
    shape: "Octagonal",
    pattern: "Faceted border",
    isSet: false,
    pairsCount: 1,
    stock: 10,
    sku: "CK-SIG-004",
    featured: true,
    hasPhotography: true,
  },
  {
    id: "s-5",
    name: "Signature Azure Wave Enamel Cufflinks",
    slug: "signature-azure-wave-enamel-cufflinks",
    category: "Signature",
    categorySlug: "signature",
    description: "Delicate wave motifs etched under translucent marine blue enamel. Smooth tactile touch.",
    price: 1280,
    images: ["/products/signature 5.jpeg"],
    material: "Silver-tone metal, blue enamel",
    finish: "Polished with engraving",
    color: "Silver, Blue",
    shape: "Rectangular",
    pattern: "Wave texture",
    isSet: false,
    pairsCount: 1,
    stock: 12,
    sku: "CK-SIG-005",
    featured: false,
    hasPhotography: true,
  },
  {
    id: "s-6",
    name: "Signature Architectural Grid Cufflinks",
    slug: "signature-architectural-grid-cufflinks",
    category: "Signature",
    categorySlug: "signature",
    description: "Multi-layered square matrix cut deep into gunmetal for modern sartorial dressers.",
    price: 1180,
    images: ["/products/signature 6.jpeg"],
    material: "Gunmetal finish",
    finish: "Engraved",
    color: "Gunmetal",
    shape: "Square",
    pattern: "Architectural grid",
    isSet: false,
    pairsCount: 1,
    stock: 15,
    sku: "CK-SIG-006",
    featured: false,
    hasPhotography: true,
  },
  {
    id: "s-7",
    name: "Signature Imperial Gold Laurel Cufflinks",
    slug: "signature-imperial-gold-laurel-cufflinks",
    category: "Signature",
    categorySlug: "signature",
    description: "Delicate laurel leaf wreath relief encircling a satin gold medallion face.",
    price: 1380,
    images: ["/products/signature 7.jpeg"],
    material: "Gold-tone metal",
    finish: "Relief engraved",
    color: "Gold",
    shape: "Circular",
    pattern: "Laurel wreath",
    isSet: false,
    pairsCount: 1,
    stock: 13,
    sku: "CK-SIG-007",
    featured: true,
    hasPhotography: true,
  },
  {
    id: "s-8",
    name: "Signature Cobalt Starburst Cufflinks",
    slug: "signature-cobalt-starburst-cufflinks",
    category: "Signature",
    categorySlug: "signature",
    description: "Brilliant royal blue starburst engraving leveled flush with high-shine chrome perimeter.",
    price: 1250,
    images: ["/products/signature 8.jpeg", "/products/signature 8+.jpeg"],
    material: "Silver-tone metal, cobalt enamel",
    finish: "Engraved",
    color: "Silver, Cobalt",
    shape: "Circular",
    pattern: "Starburst engraving",
    isSet: false,
    pairsCount: 1,
    stock: 17,
    sku: "CK-SIG-008",
    featured: true,
    hasPhotography: true,
  },
  {
    id: "s-9",
    name: "Signature Tuxedo Checkered Cufflinks",
    slug: "signature-tuxedo-checkered-cufflinks",
    category: "Signature",
    categorySlug: "signature",
    description: "Micro-checkered monochrome chessboard pattern precision-filled with black and rhodium.",
    price: 1220,
    images: ["/products/signature 9.jpeg"],
    material: "Silver-tone metal, black enamel",
    finish: "Polished",
    color: "Silver, Black",
    shape: "Square",
    pattern: "Checkered inlay",
    isSet: false,
    pairsCount: 1,
    stock: 10,
    sku: "CK-SIG-009",
    featured: false,
    hasPhotography: true,
  },
  {
    id: "s-10",
    name: "Signature Honeycomb Brass Cufflinks",
    slug: "signature-honeycomb-brass-cufflinks",
    category: "Signature",
    categorySlug: "signature",
    description: "Geometric hexagonal cell relief with micro-beveled borders and calibrated weight.",
    price: 1150,
    images: ["/products/signature 10.jpeg"],
    material: "Gold-tone metal",
    finish: "Engraved",
    color: "Gold",
    shape: "Hexagonal",
    pattern: "Honeycomb repeat",
    isSet: false,
    pairsCount: 1,
    stock: 14,
    sku: "CK-SIG-010",
    featured: false,
    hasPhotography: true,
  },
  {
    id: "s-11",
    name: "Signature Lapis Lazuli Tone Cufflinks",
    slug: "signature-lapis-lazuli-tone-cufflinks",
    category: "Signature",
    categorySlug: "signature",
    description: "Swirled midnight blue stone aesthetic encased in an elegant gold bezel.",
    price: 1390,
    images: ["/products/signature 11.jpeg"],
    material: "Gold-tone metal, composite stone",
    finish: "Polished",
    color: "Gold, Blue",
    shape: "Oval",
    pattern: "Stone grain",
    isSet: false,
    pairsCount: 1,
    stock: 9,
    sku: "CK-SIG-011",
    featured: false,
    hasPhotography: true,
  },
  {
    id: "s-12",
    name: "Signature Gunmetal Rope Border Cufflinks",
    slug: "signature-gunmetal-rope-border-cufflinks",
    category: "Signature",
    categorySlug: "signature",
    description: "Textured rope-twist outer rim framing a dark brushed titanium-tone face.",
    price: 1190,
    images: ["/products/signature 12.jpeg"],
    material: "Gunmetal finish",
    finish: "Textured border",
    color: "Gunmetal",
    shape: "Circular",
    pattern: "Rope twist",
    isSet: false,
    pairsCount: 1,
    stock: 12,
    sku: "CK-SIG-012",
    featured: false,
    hasPhotography: true,
  },
  {
    id: "s-13",
    name: "Signature Crimson Accent Enamel Cufflinks",
    slug: "signature-crimson-accent-enamel-cufflinks",
    category: "Signature",
    categorySlug: "signature",
    description: "Deep burgundy enamel with central brass medallion crafted for celebratory evening wear.",
    price: 1260,
    images: ["/products/signature 13.jpeg"],
    material: "Gold-tone metal, deep wine enamel",
    finish: "Polished",
    color: "Gold, Burgundy",
    shape: "Square",
    pattern: "Wine enamel medallion",
    isSet: false,
    pairsCount: 1,
    stock: 8,
    sku: "CK-SIG-013",
    featured: false,
    hasPhotography: true,
  },
  {
    id: "s-14",
    name: "Signature Herringbone Pattern Cufflinks",
    slug: "signature-herringbone-pattern-cufflinks",
    category: "Signature",
    categorySlug: "signature",
    description: "Subtle sartorial chevron herringbone weave engraved on silver-tone metal.",
    price: 1220,
    images: ["/products/signature 14.jpeg"],
    material: "Silver-tone metal",
    finish: "Engraved",
    color: "Silver",
    shape: "Rectangular",
    pattern: "Herringbone chevron",
    isSet: false,
    pairsCount: 1,
    stock: 16,
    sku: "CK-SIG-014",
    featured: false,
    hasPhotography: true,
  },
  {
    id: "s-15",
    name: "Signature Florentine Textured Cufflinks",
    slug: "signature-florentine-textured-cufflinks",
    category: "Signature",
    categorySlug: "signature",
    description: "Traditional cross-hatch Florentine hand finish offering an antique matte gold luster.",
    price: 1320,
    images: ["/products/signature 15.jpeg"],
    material: "Gold-tone metal",
    finish: "Florentine texture",
    color: "Gold",
    shape: "Square",
    pattern: "Cross-hatch",
    isSet: false,
    pairsCount: 1,
    stock: 11,
    sku: "CK-SIG-015",
    featured: false,
    hasPhotography: true,
  },
  {
    id: "s-16",
    name: "Signature Onyx Bar Inset Cufflinks",
    slug: "signature-onyx-bar-inset-cufflinks",
    category: "Signature",
    categorySlug: "signature",
    description: "Twin horizontal onyx enamel bars embedded into a solid silver-plated foundation.",
    price: 1200,
    images: ["/products/signature 16.jpeg"],
    material: "Silver-tone metal, black enamel",
    finish: "Polished",
    color: "Silver, Black",
    shape: "Rectangular",
    pattern: "Dual bar inlay",
    isSet: false,
    pairsCount: 1,
    stock: 15,
    sku: "CK-SIG-016",
    featured: false,
    hasPhotography: true,
  },
  {
    id: "s-17",
    name: "Signature Champagne Brass Radial Cufflinks",
    slug: "signature-champagne-brass-radial-cufflinks",
    category: "Signature",
    categorySlug: "signature",
    description: "Concentric circular grooving emanating from center with polished bevel rim.",
    price: 1270,
    images: ["/products/signature 17.jpeg"],
    material: "Gold-tone metal",
    finish: "Engraved",
    color: "Gold",
    shape: "Circular",
    pattern: "Concentric radial",
    isSet: false,
    pairsCount: 1,
    stock: 13,
    sku: "CK-SIG-017",
    featured: false,
    hasPhotography: true,
  },
  {
    id: "s-18",
    name: "Signature Carbon Fiber Weave Cufflinks",
    slug: "signature-carbon-fiber-weave-cufflinks",
    category: "Signature",
    categorySlug: "signature",
    description: "Modern twill weave texture under crystal-clear resin dome in dark gunmetal casing.",
    price: 1340,
    images: ["/products/signature 18.jpeg"],
    material: "Gunmetal finish, composite weave",
    finish: "Resin coated",
    color: "Gunmetal, Black",
    shape: "Square",
    pattern: "Twill weave",
    isSet: false,
    pairsCount: 1,
    stock: 10,
    sku: "CK-SIG-018",
    featured: false,
    hasPhotography: true,
  },
  {
    id: "s-19",
    name: "Signature Nautical Anchor Crest Cufflinks",
    slug: "signature-nautical-anchor-crest-cufflinks",
    category: "Signature",
    categorySlug: "signature",
    description: "Sculpted anchor crest raised against a dark blue vitreous enamel background.",
    price: 1360,
    images: ["/products/signature 19.jpeg"],
    material: "Silver-tone metal, blue enamel",
    finish: "Relief engraved",
    color: "Silver, Blue",
    shape: "Oval",
    pattern: "Crest relief",
    isSet: false,
    pairsCount: 1,
    stock: 8,
    sku: "CK-SIG-019",
    featured: false,
    hasPhotography: true,
  },
  {
    id: "s-20",
    name: "Signature Geometric Diamond Cut Cufflinks",
    slug: "signature-geometric-diamond-cut-cufflinks",
    category: "Signature",
    categorySlug: "signature",
    description: "Precision diamond-cut faceting across dark charcoal surface catching sharp light rays.",
    price: 1290,
    images: ["/products/signature 20.jpeg"],
    material: "Gunmetal finish",
    finish: "Faceted cut",
    color: "Gunmetal",
    shape: "Rectangular",
    pattern: "Diamond cut facet",
    isSet: false,
    pairsCount: 1,
    stock: 14,
    sku: "CK-SIG-020",
    featured: false,
    hasPhotography: true,
  },
  {
    id: "s-21",
    name: "Signature Vintage Gilded Coin Cufflinks",
    slug: "signature-vintage-gilded-coin-cufflinks",
    category: "Signature",
    categorySlug: "signature",
    description: "Antiqued coin engraving with serrated outer rim and heavyweight toggle backing.",
    price: 1350,
    images: ["/products/signature 21.jpeg"],
    material: "Gold-tone metal",
    finish: "Antique polish",
    color: "Gold",
    shape: "Circular",
    pattern: "Coin relief",
    isSet: false,
    pairsCount: 1,
    stock: 11,
    sku: "CK-SIG-021",
    featured: false,
    hasPhotography: true,
  },
  {
    id: "s-22",
    name: "Signature Silver Chevron Weave Cufflinks",
    slug: "signature-silver-chevron-weave-cufflinks",
    category: "Signature",
    categorySlug: "signature",
    description: "Intersecting silver ribbons with wire-brushed valleys and mirror-polished peaks.",
    price: 1230,
    images: ["/products/signature 22.jpeg"],
    material: "Silver-tone metal",
    finish: "Textured weave",
    color: "Silver",
    shape: "Square",
    pattern: "Chevron weave",
    isSet: false,
    pairsCount: 1,
    stock: 12,
    sku: "CK-SIG-022",
    featured: false,
    hasPhotography: true,
  },
  {
    id: "s-23",
    name: "Signature Blue Mother of Pearl Tone Cufflinks",
    slug: "signature-blue-mother-of-pearl-tone-cufflinks",
    category: "Signature",
    categorySlug: "signature",
    description: "Iridescent sapphire sheen framed by clean silver border for evening receptions.",
    price: 1400,
    images: ["/products/signature 23.jpeg"],
    material: "Silver-tone metal, pearlescent enamel",
    finish: "Polished",
    color: "Silver, Iridescent Blue",
    shape: "Circular",
    pattern: "Pearlescent shimmer",
    isSet: false,
    pairsCount: 1,
    stock: 7,
    sku: "CK-SIG-023",
    featured: false,
    hasPhotography: true,
  },
  {
    id: "s-24",
    name: "Signature Roman Pillar Filigree Cufflinks",
    slug: "signature-roman-pillar-filigree-cufflinks",
    category: "Signature",
    categorySlug: "signature",
    description: "Vertical fluting inspired by classical architectural pillars in rich brass plating.",
    price: 1260,
    images: ["/products/signature 24.jpeg"],
    material: "Gold-tone metal",
    finish: "Fluted engraved",
    color: "Gold",
    shape: "Rectangular",
    pattern: "Fluted pillar",
    isSet: false,
    pairsCount: 1,
    stock: 15,
    sku: "CK-SIG-024",
    featured: false,
    hasPhotography: true,
  },
  {
    id: "s-25",
    name: "Signature Matte Black Edge Polish Cufflinks",
    slug: "signature-matte-black-edge-polish-cufflinks",
    category: "Signature",
    categorySlug: "signature",
    description: "Sandblasted matte black central square with contrasting razor-thin silver border.",
    price: 1190,
    images: ["/products/signature 25.jpeg"],
    material: "Gunmetal finish, silver accents",
    finish: "Matte & Polished",
    color: "Gunmetal, Silver",
    shape: "Square",
    pattern: "Contrast border",
    isSet: false,
    pairsCount: 1,
    stock: 13,
    sku: "CK-SIG-025",
    featured: false,
    hasPhotography: true,
  },
  {
    id: "s-26",
    name: "Signature Royal Fleur-de-lis Cufflinks",
    slug: "signature-royal-fleur-de-lis-cufflinks",
    category: "Signature",
    categorySlug: "signature",
    description: "Classic European heraldic crest engraved in silver against deep onyx background.",
    price: 1380,
    images: ["/products/signature 26.jpeg"],
    material: "Silver-tone metal, black enamel",
    finish: "Engraved crest",
    color: "Silver, Black",
    shape: "Shield",
    pattern: "Fleur-de-lis",
    isSet: false,
    pairsCount: 1,
    stock: 9,
    sku: "CK-SIG-026",
    featured: false,
    hasPhotography: true,
  },
  {
    id: "s-27",
    name: "Signature Golden Lattice Mesh Cufflinks",
    slug: "signature-golden-lattice-mesh-cufflinks",
    category: "Signature",
    categorySlug: "signature",
    description: "Crossed lattice pattern cut with diamond precision on warm gold-tone metal.",
    price: 1250,
    images: ["/products/signature 27.jpeg"],
    material: "Gold-tone metal",
    finish: "Engraved",
    color: "Gold",
    shape: "Square",
    pattern: "Lattice mesh",
    isSet: false,
    pairsCount: 1,
    stock: 12,
    sku: "CK-SIG-027",
    featured: false,
    hasPhotography: true,
  },
  {
    id: "s-28",
    name: "Signature Deep Navy Stepped Cufflinks",
    slug: "signature-deep-navy-stepped-cufflinks",
    category: "Signature",
    categorySlug: "signature",
    description: "Three-tiered architectural stepped structure holding navy mineral enamel.",
    price: 1310,
    images: ["/products/signature 28.jpeg"],
    material: "Silver-tone metal, navy enamel",
    finish: "Stepped bevel",
    color: "Silver, Navy",
    shape: "Rectangular",
    pattern: "Tiered step",
    isSet: false,
    pairsCount: 1,
    stock: 11,
    sku: "CK-SIG-028",
    featured: false,
    hasPhotography: true,
  },
  {
    id: "s-29",
    name: "Signature Obsidian Brushed Titanium Tone Cufflinks",
    slug: "signature-obsidian-brushed-titanium-tone-cufflinks",
    category: "Signature",
    categorySlug: "signature",
    description: "Contemporary dark finish with dual brushed diagonal zones and filed beveled rims.",
    price: 1280,
    images: ["/products/signature 29.jpeg"],
    material: "Gunmetal finish",
    finish: "Diagonal brush",
    color: "Gunmetal",
    shape: "Square",
    pattern: "Diagonal split",
    isSet: false,
    pairsCount: 1,
    stock: 14,
    sku: "CK-SIG-029",
    featured: false,
    hasPhotography: true,
  },
  {
    id: "s-30",
    name: "Signature Sovereign Gold Medallion Cufflinks",
    slug: "signature-sovereign-gold-medallion-cufflinks",
    category: "Signature",
    categorySlug: "signature",
    description: "Sovereign star medallion raised in warm brass with beaded outer halo rim.",
    price: 1370,
    images: ["/products/signature 30.jpeg"],
    material: "Gold-tone metal",
    finish: "Relief & beaded",
    color: "Gold",
    shape: "Circular",
    pattern: "Star medallion",
    isSet: false,
    pairsCount: 1,
    stock: 8,
    sku: "CK-SIG-030",
    featured: false,
    hasPhotography: true,
  },
  {
    id: "s-31",
    name: "Signature Silver Barleycorn Pattern Cufflinks",
    slug: "signature-silver-barleycorn-pattern-cufflinks",
    category: "Signature",
    categorySlug: "signature",
    description: "Classic watchmaker barleycorn engraving creating fine micro-facets across silver.",
    price: 1290,
    images: ["/products/signature 31.jpeg"],
    material: "Silver-tone metal",
    finish: "Barleycorn engraving",
    color: "Silver",
    shape: "Oval",
    pattern: "Barleycorn grain",
    isSet: false,
    pairsCount: 1,
    stock: 10,
    sku: "CK-SIG-031",
    featured: false,
    hasPhotography: true,
  },
  {
    id: "s-32",
    name: "Signature Gunmetal Black Hexagon Cufflinks",
    slug: "signature-gunmetal-black-hexagon-cufflinks",
    category: "Signature",
    categorySlug: "signature",
    description: "Masculine hexagonal geometry with deep black enamel center and chamfered edges.",
    price: 1240,
    images: ["/products/signature 32.jpeg"],
    material: "Gunmetal finish, black enamel",
    finish: "Polished",
    color: "Gunmetal, Black",
    shape: "Hexagonal",
    pattern: "Hexagonal inset",
    isSet: false,
    pairsCount: 1,
    stock: 13,
    sku: "CK-SIG-032",
    featured: false,
    hasPhotography: true,
  },
  {
    id: "s-33",
    name: "Signature Polished Onyx Disc Cufflinks",
    slug: "signature-polished-onyx-disc-cufflinks",
    category: "Signature",
    categorySlug: "signature",
    description: "Sleek circular black enamel center ringed by warm champagne gold borders.",
    price: 1350,
    images: ["/products/signature 33.jpeg"],
    material: "Gold-tone metal, black enamel",
    finish: "Polished",
    color: "Gold, Black",
    shape: "Circular",
    pattern: "Concentric ring",
    isSet: false,
    pairsCount: 1,
    stock: 15,
    sku: "CK-SIG-033",
    featured: false,
    hasPhotography: true,
  },

  // ==========================================
  // PREMIUM COLLECTION (17 Products: Rs. 1,500 - 2,500)
  // ==========================================
  {
    id: "p-1",
    name: "Premium Pavé Crystal Gold Octagon Cufflinks",
    slug: "premium-pave-crystal-gold-octagon-cufflinks",
    category: "Premium",
    categorySlug: "premium",
    description: "Hand-set crystal pavé border encircling an ivory porcelain center with mirror-finished gold casing.",
    price: 2450,
    images: ["/products/premium 1.jpeg"],
    material: "Gold-tone metal, crystal pavé, ivory enamel",
    finish: "Polished with pavé border",
    color: "Gold, Ivory",
    shape: "Octagonal",
    pattern: "Pavé crystal border",
    isSet: false,
    pairsCount: 1,
    stock: 8,
    sku: "CK-PRM-001",
    featured: true,
    hasPhotography: true,
  },
  {
    id: "p-2",
    name: "Premium Royal Blue Enamel Filigree Cufflinks",
    slug: "premium-royal-blue-enamel-filigree-cufflinks",
    category: "Premium",
    categorySlug: "premium",
    description: "Deep vitreous blue enamel with fine hand-engraved acanthus filigree in rhodium plating.",
    price: 2100,
    images: ["/products/premium 2.jpeg"],
    material: "Silver-tone metal, royal blue enamel",
    finish: "Polished & filigree",
    color: "Silver, Blue",
    shape: "Circular",
    pattern: "Acanthus engraving",
    isSet: false,
    pairsCount: 1,
    stock: 11,
    sku: "CK-PRM-002",
    featured: true,
    hasPhotography: true,
  },
  {
    id: "p-3",
    name: "Premium Diamond Cut Onyx Cushion Cufflinks",
    slug: "premium-diamond-cut-onyx-cushion-cufflinks",
    category: "Premium",
    categorySlug: "premium",
    description: "Cushion cut silhouette with faceted black stone face and precision diamond cut bezel.",
    price: 2250,
    images: ["/products/premium 3.jpeg"],
    material: "Silver-tone metal, black stone",
    finish: "Faceted cut",
    color: "Silver, Black",
    shape: "Cushion",
    pattern: "Faceted crystal cuts",
    isSet: false,
    pairsCount: 1,
    stock: 9,
    sku: "CK-PRM-003",
    featured: true,
    hasPhotography: true,
  },
  {
    id: "p-4",
    name: "Premium Mother of Pearl Pavé Halo Cufflinks",
    slug: "premium-mother-of-pearl-pave-halo-cufflinks",
    category: "Premium",
    categorySlug: "premium",
    description: "Natural mother of pearl face surrounded by a micro-pavé crystal halo in champagne brass.",
    price: 2350,
    images: ["/products/premium 4.jpeg"],
    material: "Gold-tone metal, mother of pearl, crystal pavé",
    finish: "Pavé setting",
    color: "Gold, Pearl",
    shape: "Circular",
    pattern: "Pavé halo",
    isSet: false,
    pairsCount: 1,
    stock: 7,
    sku: "CK-PRM-004",
    featured: true,
    hasPhotography: true,
  },
  {
    id: "p-5",
    name: "Premium Black Diamond Faceted Gunmetal Cufflinks",
    slug: "premium-black-diamond-faceted-gunmetal-cufflinks",
    category: "Premium",
    categorySlug: "premium",
    description: "Architectural 3D faceted geometry with smoked stone inlays and hand-buffed dark gunmetal.",
    price: 1950,
    images: ["/products/premium 5.jpeg", "/products/premium 5+.jpeg"],
    material: "Gunmetal finish, smoked crystal",
    finish: "Faceted geometric",
    color: "Gunmetal, Smoked Black",
    shape: "Square",
    pattern: "3D faceted pyramid",
    isSet: false,
    pairsCount: 1,
    stock: 12,
    sku: "CK-PRM-005",
    featured: true,
    hasPhotography: true,
  },
  {
    id: "p-6",
    name: "Premium Gilded Trellis Crystal Cufflinks",
    slug: "premium-gilded-trellis-crystal-cufflinks",
    category: "Premium",
    categorySlug: "premium",
    description: "Intricate openwork trellis filigree with bezel-set corner crystals in 24k gold plating.",
    price: 2200,
    images: ["/products/premium 6.jpeg"],
    material: "Gold-tone metal, fine crystals",
    finish: "Openwork filigree",
    color: "Gold",
    shape: "Rectangular",
    pattern: "Lattice trellis",
    isSet: false,
    pairsCount: 1,
    stock: 10,
    sku: "CK-PRM-006",
    featured: false,
    hasPhotography: true,
  },
  {
    id: "p-7",
    name: "Premium Sapphire Starburst Beveled Cufflinks",
    slug: "premium-sapphire-starburst-beveled-cufflinks",
    category: "Premium",
    categorySlug: "premium",
    description: "Deep blue sunburst enamel dial with raised rhodium markers and mirror-polished edge cuts.",
    price: 1850,
    images: ["/products/premium 7.jpeg"],
    material: "Silver-tone metal, deep blue enamel",
    finish: "Sunburst dial",
    color: "Silver, Blue",
    shape: "Circular",
    pattern: "Radial dial markers",
    isSet: false,
    pairsCount: 1,
    stock: 13,
    sku: "CK-PRM-007",
    featured: false,
    hasPhotography: true,
  },
  {
    id: "p-8",
    name: "Premium Art Deco Emerald Cut Cufflinks",
    slug: "premium-art-deco-emerald-cut-cufflinks",
    category: "Premium",
    categorySlug: "premium",
    description: "Art Deco emerald-cut rectangular stone encased in dual-step stepped brass frame.",
    price: 2400,
    images: ["/products/premium 8.jpeg", "/products/premium 8+.jpeg"],
    material: "Gold-tone metal, emerald-cut composite",
    finish: "Art Deco stepped",
    color: "Gold, Deep Green",
    shape: "Rectangular",
    pattern: "Emerald step cut",
    isSet: false,
    pairsCount: 1,
    stock: 8,
    sku: "CK-PRM-008",
    featured: true,
    hasPhotography: true,
  },
  {
    id: "p-9",
    name: "Premium Noir Dual Crystal Row Cufflinks",
    slug: "premium-noir-dual-crystal-row-cufflinks",
    category: "Premium",
    categorySlug: "premium",
    description: "Twin vertical channels of channel-set crystals embedded in midnight gunmetal casing.",
    price: 2150,
    images: ["/products/premium 9.jpeg", "/products/premium 9+.jpeg"],
    material: "Gunmetal finish, channel crystals",
    finish: "Channel set",
    color: "Gunmetal, Clear Crystal",
    shape: "Rectangular",
    pattern: "Dual channel rows",
    isSet: false,
    pairsCount: 1,
    stock: 11,
    sku: "CK-PRM-009",
    featured: true,
    hasPhotography: true,
  },
  {
    id: "p-10",
    name: "Premium Sovereign Star Pavé Cufflinks",
    slug: "premium-sovereign-star-pave-cufflinks",
    category: "Premium",
    categorySlug: "premium",
    description: "Eight-pointed sovereign star set with central crystal cluster against satin finish.",
    price: 2500,
    images: ["/products/Premium 10.jpeg"],
    material: "Gold-tone metal, crystal pavé",
    finish: "Relief pavé",
    color: "Gold",
    shape: "Circular",
    pattern: "Sovereign star",
    isSet: false,
    pairsCount: 1,
    stock: 6,
    sku: "CK-PRM-010",
    featured: true,
    hasPhotography: true,
  },
  {
    id: "p-11",
    name: "Premium Midnight Velvet Enamel Cufflinks",
    slug: "premium-midnight-velvet-enamel-cufflinks",
    category: "Premium",
    categorySlug: "premium",
    description: "Deep opaque black enamel polished to a mirror reflection with platinum-plated bevels.",
    price: 1750,
    images: ["/products/premium 11.jpeg"],
    material: "Silver-tone metal, black enamel",
    finish: "Mirror enamel",
    color: "Silver, Black",
    shape: "Square",
    pattern: "Seamless mirror face",
    isSet: false,
    pairsCount: 1,
    stock: 14,
    sku: "CK-PRM-011",
    featured: false,
    hasPhotography: true,
  },
  {
    id: "p-12",
    name: "Premium Imperial Crest Engraved Cufflinks",
    slug: "premium-imperial-crest-engraved-cufflinks",
    category: "Premium",
    categorySlug: "premium",
    description: "Custom artisan hand engraving depicting formal royal insignia on heavy brass base.",
    price: 2300,
    images: ["/products/premium 12.jpeg"],
    material: "Gold-tone metal",
    finish: "Hand-engraved",
    color: "Gold",
    shape: "Shield",
    pattern: "Heraldic crest",
    isSet: false,
    pairsCount: 1,
    stock: 9,
    sku: "CK-PRM-012",
    featured: false,
    hasPhotography: true,
  },
  {
    id: "p-13",
    name: "Premium Azure Mosaic Enamel Cufflinks",
    slug: "premium-azure-mosaic-enamel-cufflinks",
    category: "Premium",
    categorySlug: "premium",
    description: "Multi-tonal blue mosaic glass tiles fired into silver cells for bespoke formal evenings.",
    price: 2100,
    images: ["/products/premium 13.jpeg"],
    material: "Silver-tone metal, mosaic enamel",
    finish: "Mosaic cloisonné",
    color: "Silver, Azure",
    shape: "Square",
    pattern: "Geometric mosaic",
    isSet: false,
    pairsCount: 1,
    stock: 8,
    sku: "CK-PRM-013",
    featured: false,
    hasPhotography: true,
  },
  {
    id: "p-14",
    name: "Premium Rose Gold Brushed Hexagon Cufflinks",
    slug: "premium-rose-gold-brushed-hexagon-cufflinks",
    category: "Premium",
    categorySlug: "premium",
    description: "Warm rose gold tone with satin wire brushing and sharp high-polish chamfers.",
    price: 1650,
    images: ["/products/premium 14.jpeg"],
    material: "Rose gold-tone metal",
    finish: "Brushed & chamfered",
    color: "Rose Gold",
    shape: "Hexagonal",
    pattern: "Satin grain",
    isSet: false,
    pairsCount: 1,
    stock: 15,
    sku: "CK-PRM-014",
    featured: false,
    hasPhotography: true,
  },
  {
    id: "p-15",
    name: "Premium Pavé Crystal Noir Border Cufflinks",
    slug: "premium-pave-crystal-noir-border-cufflinks",
    category: "Premium",
    categorySlug: "premium",
    description: "Deep black onyx center encircled by a double row of sparkling micropavé crystals.",
    price: 2480,
    images: ["/products/premium 15.jpeg", "/products/premium 15 +.jpeg"],
    material: "Silver-tone metal, black onyx, crystals",
    finish: "Double pavé setting",
    color: "Silver, Black",
    shape: "Circular",
    pattern: "Double pavé ring",
    isSet: false,
    pairsCount: 1,
    stock: 7,
    sku: "CK-PRM-015",
    featured: true,
    hasPhotography: true,
  },
  {
    id: "p-16",
    name: "Premium Golden Sunburst Medallion Cufflinks",
    slug: "premium-golden-sunburst-medallion-cufflinks",
    category: "Premium",
    categorySlug: "premium",
    description: "Masterwork deep relief sunburst with raised center crystal and coin-edge perimeter.",
    price: 2400,
    images: ["/products/premium 16.jpeg", "/products/premium 16 +.jpeg"],
    material: "Gold-tone metal, central crystal",
    finish: "Deep relief & coin edge",
    color: "Gold",
    shape: "Circular",
    pattern: "Sunburst medallion",
    isSet: false,
    pairsCount: 1,
    stock: 8,
    sku: "CK-PRM-016",
    featured: true,
    hasPhotography: true,
  },
  {
    id: "p-17",
    name: "Premium Damascus Steel Texture Cufflinks",
    slug: "premium-damascus-steel-texture-cufflinks",
    category: "Premium",
    categorySlug: "premium",
    description: "Intricate organic folded steel wave pattern with satin gunmetal protective coat.",
    price: 2250,
    images: ["/products/premium 17.jpeg"],
    material: "Gunmetal finish",
    finish: "Damascus etched",
    color: "Gunmetal, Charcoal",
    shape: "Rectangular",
    pattern: "Damascus wave",
    isSet: false,
    pairsCount: 1,
    stock: 10,
    sku: "CK-PRM-017",
    featured: false,
    hasPhotography: true,
  },
];

// Data access functions
export function getAllProducts(): Product[] {
  return products;
}

export function getFeaturedProducts(): Product[] {
  return products.filter((product) => product.featured);
}

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((product) => product.slug === slug);
}

export function getProductsByCategory(categorySlug: string): Product[] {
  const lowerSlug = categorySlug.toLowerCase().trim();
  return products.filter((product) => product.categorySlug === lowerSlug || product.category.toLowerCase() === lowerSlug);
}

export function searchProducts(query: string): Product[] {
  if (!query || !query.trim()) return [];
  const lowerQuery = query.toLowerCase().trim();
  return products.filter(
    (product) =>
      product.name.toLowerCase().includes(lowerQuery) ||
      product.description.toLowerCase().includes(lowerQuery) ||
      product.category.toLowerCase().includes(lowerQuery) ||
      product.material.toLowerCase().includes(lowerQuery) ||
      product.finish.toLowerCase().includes(lowerQuery) ||
      product.color.toLowerCase().includes(lowerQuery) ||
      product.pattern.toLowerCase().includes(lowerQuery)
  );
}

// Collection data
export interface Category {
  name: CollectionCategory;
  slug: CollectionSlug;
  description: string;
  priceRange: string;
}

export const categories: Category[] = [
  {
    name: "Classical",
    slug: "classical",
    description: "Essential formal cufflinks with a clean finish and timeless proportions.",
    priceRange: "Rs. 700–800",
  },
  {
    name: "Signature",
    slug: "signature",
    description: "Refined details, rich mineral enamel, and subtle surface textures.",
    priceRange: "Rs. 1,000–1,400",
  },
  {
    name: "Premium",
    slug: "premium",
    description: "Artisanal pieces featuring fine engraving, crystal pavé, and stone detailing.",
    priceRange: "Rs. 1,500–2,500",
  },
];
